version: 2
updates:
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: uvicorn
    versions:
    - 0.13.4
  - dependency-name: aiofiles
    versions:
    - 0.6.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.10
    - 13.0.13
    - 13.0.7
    - 13.1.2
  - dependency-name: react-dom
    versions:
    - 16.14.0
  - dependency-name: react-scripts
    versions:
    - 4.0.3
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
  - dependency-name: jquery
    versions:
    - 3.6.0
