version: '3.8'


services:
    backend:
        build: 
            context: "./backend"
            dockerfile: Dockerfile
        ports:
            - "5000:5000"

    frontend:
        stdin_open: true
        build:
            context: "./frontend"
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
